import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';import {verifyTransport,canonical} from '../src/verifier.mjs';
const sample=JSON.parse(readFileSync(new URL('../demo/sample.json',import.meta.url),'utf8'));
const cases=[['clean',x=>{},'VALID'],['one-byte payload change',x=>x.files['measurement.json']=x.files['measurement.json'].replace('420','421'),'INVALID'],['receipt decision substitution',x=>{let r=JSON.parse(x.files['receipt.json']);r.verdict.value='allow';x.files['receipt.json']=JSON.stringify(r);},'INVALID'],['missing locked ledger',x=>delete x.files['ledger.jsonl'],'INVALID'],['clock downgrade',x=>{let r=JSON.parse(x.files['receipt.json']);r.clock.value='unset';r.generated_at='unset';x.files['receipt.json']=JSON.stringify(r);},'INVALID'],['malformed control',x=>x.files['manifest.json']='[]','INVALID'],['malformed receipt',x=>x.files['receipt.json']='null','INVALID'],['duplicate manifest file',x=>{let m=JSON.parse(x.files['manifest.json']);m.files.push(m.files[0]);x.files['manifest.json']=JSON.stringify(m);},'INVALID']];
for(const [name,mutate,expected] of cases){const t=structuredClone(sample);mutate(t);const r=await verifyTransport(t);assert.equal(r.status,expected,name);console.log(name+': '+r.status);}
assert.equal(canonical({text:'e\u0301',arabic:'سلام'}),'{"arabic":"\\u0633\\u0644\\u0627\\u0645","text":"\\u00e9"}');assert.throws(()=>canonical(1.5));console.log('Unicode parity and unsupported numeric profile: PASS');
import {createHash} from 'node:crypto';import {sha256Fallback} from '../src/sha256.mjs';
for(const s of ['', 'abc','سلام','e\u0301','😀','a'.repeat(55),'a'.repeat(56),'a'.repeat(63),'a'.repeat(64),'a'.repeat(65),'a'.repeat(1000000)])assert.equal(sha256Fallback(new TextEncoder().encode(s)),createHash('sha256').update(s).digest('hex'));
console.log('Fallback SHA-256 against Node crypto: 11 vectors PASS');
const saved=globalThis.crypto;Object.defineProperty(globalThis,'crypto',{value:undefined,configurable:true});assert.equal((await verifyTransport(sample)).status,'VALID');Object.defineProperty(globalThis,'crypto',{value:saved,configurable:true});console.log('Offline fallback end-to-end: PASS');
